# Generated by Django 4.2.1 on 2023-05-26 02:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_answer_modify_date_question_modify_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="topics",
            name="modify_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
